services:
  - type: web
    name: plataforma-credito
    runtime: docker
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: DataSource=app.db;Cache=Shared
      - key: Redis__ConnectionString
        sync: false
